AWSTemplateFormatVersion: 2010-09-09
Description: 'RDS and any other resources that a service needs.'
Parameters:
  EnvironmentName:
    Type: String
    Default: base-staging
    Description: >-
      The environment name, used for locating outputs from the prerequisite
      stacks
  DBMasterUsername:
    Type: String
    Description: >-
      The environment name, used for locating outputs from the prerequisite
      stacks
  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: >-
      The environment name, used for locating outputs from the prerequisite
      stacks
Resources:
  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Backend db subnet group that allows for multi-az
      SubnetIds:
        - 'Fn::ImportValue': !Join 
            - ':'
            - - !Ref EnvironmentName
              - PublicSubnetOne
        - 'Fn::ImportValue': !Join 
            - ':'
            - - !Ref EnvironmentName
              - PublicSubnetTwo
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c9b06575-4cbc-4564-8b51-a09c779746e7
  Database:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: 10.5
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 10
      StorageType: gp2
      AllowMajorVersionUpgrade: true
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8240c766-9a00-4cfa-a751-cbf83deb3fa7
  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: DB Security Group
      VpcId:
        'Fn::ImportValue': !Join 
          - ':'
          - - !Ref EnvironmentName
            - VPCId
      SecurityGroupIngress:
        Description: Ingress from Fargate containers
        IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        SourceSecurityGroupId:
          'Fn::ImportValue': !Join 
            - ':'
            - - !Ref EnvironmentName
              - FargateContainerSecurityGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5b08427d-d7f2-4488-9a05-a3d791b1d65f
  DBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Family: postgres10
      Description: Database Parameter Group
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 231fa001-444d-481d-afa7-8c2bc417d4b0
Outputs:
  DatabaseEndpoint:
    Description: The endpoint of the postgres database
    Value: !Join 
      - ''
      - - 'postgres://'
        - !Ref DBMasterUsername
        - ':'
        - !Ref DBMasterPassword
        - '@'
        - !GetAtt Database.Endpoint.Address
    Export:
      Name: !Join
      - ':'
      - - !Ref EnvironmentName
        - DatabaseEndpoint
Metadata:
  'AWS::CloudFormation::Designer':
    e9dd6f49-d161-4e20-944c-85706515e32f:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 390
      z: 1
      embeds: []
    6e12072e-bd50-46f3-bc03-8958ae09d919:
      size:
        width: 240
        height: 240
      position:
        x: 60
        'y': 90
      z: 1
      embeds:
        - 0744e3af-97a8-4708-b3a1-ca8e23431554
    0744e3af-97a8-4708-b3a1-ca8e23431554:
      size:
        width: 60
        height: 60
      position:
        x: 90
        'y': 150
      z: 2
      parent: 6e12072e-bd50-46f3-bc03-8958ae09d919
      embeds: []
      isassociatedwith:
        - e9dd6f49-d161-4e20-944c-85706515e32f
      iscontainedinside:
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
        - 6e12072e-bd50-46f3-bc03-8958ae09d919
    c9b06575-4cbc-4564-8b51-a09c779746e7:
      size:
        width: 140
        height: 140
      position:
        x: 480
        'y': 170
      z: 0
      embeds:
        - 8240c766-9a00-4cfa-a751-cbf83deb3fa7
    8240c766-9a00-4cfa-a751-cbf83deb3fa7:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 210
      z: 1
      parent: c9b06575-4cbc-4564-8b51-a09c779746e7
      embeds: []
      isassociatedwith:
        - 231fa001-444d-481d-afa7-8c2bc417d4b0
      iscontainedinside:
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
        - c9b06575-4cbc-4564-8b51-a09c779746e7
    5b08427d-d7f2-4488-9a05-a3d791b1d65f:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 370
      z: 0
      embeds: []
    231fa001-444d-481d-afa7-8c2bc417d4b0:
      size:
        width: 60
        height: 60
      position:
        x: 660
        'y': 210
      z: 0
      embeds: []
